package com.QLSV.Ui;

/*test_tiep cai_demo*/
import com.QLSV.Utility.NhacNen;
import com.QLSV.DAO.GiangVienDAO;
import com.QLSV.DAO.LuuTaiKhoanDAO;
import com.QLSV.DAO.NhanVienDAO;
import com.QLSV.DAO.SinhVienDAO;
import com.QLSV.Model.LuuTaiKhoan;
import com.QLSV.Model.GiangVien;
import com.QLSV.Model.NhanVien;
import com.QLSV.Model.SinhVien;
import com.QLSV.Utility.MsgBox;
import com.QLSV.Utility.Auth;
import com.QLSV.Utility.XImage;
import java.awt.Color; 
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.sound.sampled.*;

/**
 *
 * @author sushi
 */
public class DangNhapFrame extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapFrame
     */
    int posX;
    int posY;
    LuuTaiKhoanDAO dao = new LuuTaiKhoanDAO();
    QuenMatKhauFrame qMkF = new QuenMatKhauFrame();

    public DangNhapFrame() throws SQLException, UnsupportedAudioFileException, IOException, LineUnavailableException {
        initComponents();
        setTaiKhoanMatKhau();
        textExample();
        realPass = txtPass.getText();
        matKhauChinh = txtPass.getText();this.setIconImage(XImage.getAppIcon());
        setPass();
//        clip.open(audio);
//        nhacNen();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(255, 255, 255, 0));
        txtUserName.setBackground(new Color(255, 255, 255, 0));
        txtPass.setBackground(new Color(255, 255, 255, 0));
        chkAgree.setBackground(new Color(255, 255, 255, 0));
        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX = e.getX();
                posY = e.getY();
            }
        });
        this.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt) {
                //sets frame position when mouse dragged			
                setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);

            }
        });
        btnCancel.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btnLogin.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblConMat = new javax.swing.JLabel();
        txtPlace = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblLoi = new javax.swing.JLabel();
        lblSound = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtUserName = new javax.swing.JTextField();
        chkAgree = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnChangePassWord = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        rightPanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        leftPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/face_id_40px.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/qr_code_25px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 40, 50));

        lblConMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTest/eye_10px.png"))); // NOI18N
        lblConMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConMatMouseClicked(evt);
            }
        });
        getContentPane().add(lblConMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, -1, -1));

        txtPlace.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        txtPlace.setForeground(new java.awt.Color(241, 241, 241));
        txtPlace.setText("vd : PS18597");
        getContentPane().add(txtPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 256, 130, 20));

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 150, 30));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 150, 30));

        lblLoi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLoi.setForeground(new java.awt.Color(238, 118, 118));
        lblLoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTest/warning.png"))); // NOI18N
        lblLoi.setText("Các ô không được để trống");
        getContentPane().add(lblLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 320, -1));

        lblSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTest/sound_30px.png")));
        lblSound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoundMouseClicked(evt);
            }
        });
        getContentPane().add(lblSound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 40));

        txtPass.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setText("123123123");
        txtPass.setBorder(null);
        txtPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtPassMouseReleased(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 320, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 320, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 320, 20));

        txtUserName.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(null);
        txtUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtUserNameMouseReleased(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 320, 50));

        chkAgree.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        chkAgree.setForeground(new java.awt.Color(255, 255, 255));
        chkAgree.setText("Remenber ");
        chkAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAgreeActionPerformed(evt);
            }
        });
        getContentPane().add(chkAgree, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 340, 40));

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTest/nut.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 160, 70));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 320, 60));

        btnChangePassWord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChangePassWord.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTest/DangXuat.png"))); // NOI18N
        btnChangePassWord.setText("Forgot Password");
        btnChangePassWord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePassWord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangePassWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangePassWordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChangePassWordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangePassWordMouseExited(evt);
            }
        });
        getContentPane().add(btnChangePassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 190, 40));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTest/nut.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 140, 50));

        rightPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTest/right_panel.png"))); // NOI18N
        getContentPane().add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, -10, 740, 670));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Come Fly With Us");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 250, 50));

        leftPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTest/left_panel.png"))); // NOI18N
        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 680, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAgreeActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_chkAgreeActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        if (MsgBox.confirm(this, "Bạn có muốn thoát không ")) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        if (chkAgree.isSelected()) {
            dao.update(getModel());
        } else {
            try {
                dao.update(new LuuTaiKhoan(dao.select().getTenDangNhap(), ""));
            } catch (SQLException ex) {
                Logger.getLogger(DangNhapFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            dangnhap();
        } catch (IOException ex) {
            Logger.getLogger(DangNhapFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnChangePassWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePassWordMouseClicked
        qMkF.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePassWordMouseClicked

    private void txtUserNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameMouseReleased

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        textExample();         // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void txtPassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassMouseReleased

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        setPass();
    }//GEN-LAST:event_txtPassKeyReleased
    int conMat = 0;
    private void lblConMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConMatMouseClicked
        if (conMat == 0) {
            txtPass.setText(realPass);
            lblConMat.setIcon(new ImageIcon(getClass().getResource("/imageTest/eye_25px.png")));
            conMat++;
        } else {
            lblConMat.setIcon(new ImageIcon(getClass().getResource("/imageTest/eye_10px.png")));
            conMat--;
        }
        setPass();
    }//GEN-LAST:event_lblConMatMouseClicked

    private void lblSoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoundMouseClicked
        NhacNen.stop();
        if (NhacNen.nhac == 1) {
            lblSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTest/sound_30px.png")));
        } else {
            lblSound.setIcon(new ImageIcon(getClass().getResource("/imageTest/foreign_language_sound_30px.png")));
        }
    }//GEN-LAST:event_lblSoundMouseClicked

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        setColor(btnCancel);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        resetColor(btnCancel);
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnChangePassWordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePassWordMouseEntered
        setColor(btnChangePassWord);
    }//GEN-LAST:event_btnChangePassWordMouseEntered

    private void btnChangePassWordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePassWordMouseExited
        resetColor(btnChangePassWord);
    }//GEN-LAST:event_btnChangePassWordMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            dangnhapbyqr();
        } catch (IOException ex) {
            Logger.getLogger(DangNhapFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        NhanDienFrame nd=new NhanDienFrame();
        nd.setVisible(true); 
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked
    void dangnhapbyqr() throws IOException {
        MakeQR qr = new MakeQR();
        qr.load();
        Menu mn = new Menu();
        mn.setVisible(true);
    }
    String realPass = "";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    //                try {
                    new ManHinhChao().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DangNhapFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(DangNhapFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(DangNhapFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(DangNhapFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void setColor(JLabel p) {
        p.setForeground(new Color(255, 250, 101));
    }

    public void resetColor(JLabel p1) {
        p1.setForeground(new Color(255, 255, 255));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnChangePassWord;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JCheckBox chkAgree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblConMat;
    private javax.swing.JLabel lblLoi;
    private javax.swing.JLabel lblSound;
    private javax.swing.JLabel leftPanel;
    private javax.swing.JLabel rightPanel;
    public javax.swing.JTextField txtPass;
    private javax.swing.JLabel txtPlace;
    public javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
    public LuuTaiKhoan getModel() {
        LuuTaiKhoan luu = new LuuTaiKhoan(txtUserName.getText(), realPass);
        return luu;
    }
    String matKhauChinh = null;
    
    void setPass() {
        String matK = txtPass.getText();
        int len = matK.length();
        matKhauChinh = matK;
        int lenR = realPass.length();

        if (conMat == 0) {
            String sao = "";
            if (len > lenR) {
                String tam = matK.substring(lenR, len);
                realPass += tam;
            } else if (len < lenR) {
                realPass = realPass.substring(0, len);
            }
            for (int i = 0; i < realPass.length(); i++) {
                sao += "*";
            }
            txtPass.setText(sao);
        } else {
            realPass = txtPass.getText();
        }
    }   
    int nhac = 0;
    File file = new File(getClass().getResource("/com/QLSV/Audio/beat.wav").getFile());
    AudioInputStream audio = AudioSystem.getAudioInputStream(file);
    Clip clip = AudioSystem.getClip();

    void nhacNen() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        if (nhac == 0) {
            lblSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTest/sound_30px.png")));
            clip.start();
            nhac++;
        } else {
            lblSound.setIcon(new ImageIcon(getClass().getResource("/imageTest/foreign_language_sound_30px.png")));
            clip.stop();
            nhac--;
        }

    }

    public void setTaiKhoanMatKhau() throws SQLException {
        LuuTaiKhoan ltk = dao.select();
        txtUserName.setText(ltk.getTenDangNhap());
        txtPass.setText(ltk.getMatKhau());
        if (ltk.getMatKhau().equals("")) {
            chkAgree.setSelected(false);
        } else {
            chkAgree.setSelected(true);
        }
    }

    public void textExample() {
        if (txtUserName.getText().equals("")) {
            txtPlace.setVisible(true);
        } else {
            txtPlace.setVisible(false);
        }
    }

    NhanVienDAO nvDAO = new NhanVienDAO();
    GiangVienDAO gvDAO = new GiangVienDAO();
    SinhVienDAO svDAO = new SinhVienDAO();
    
    void dangnhap() throws IOException {
        String user = txtUserName.getText();
        String ktuser = user.substring(0, 2);
        if (ktuser.equalsIgnoreCase("GV")) {
            GiangVien gv = gvDAO.selectByID(user);
            if (gv == null) {
                MsgBox.alert(this, "Sai tên đăng nhập!");
            } else if (!realPass.equals(gv.getMatKhau())) {
                MsgBox.alert(this, "Sai mật khẩu!");
            } else {
                Auth.USERGV = gv;
                this.dispose();
                NhapDiemFrame gdc = new NhapDiemFrame();
                gdc.setVisible(true);;

            }
        } else if (ktuser.equalsIgnoreCase("NV") || ktuser.equalsIgnoreCase("QL")) {
            NhanVien nv = nvDAO.selectByID(user);
            if (nv == null) {
                MsgBox.alert(this, "Sai tên đăng nhập!");
            } else if (!realPass.equals(nv.getMatKhau())) {
                MsgBox.alert(this, "Sai mật khẩu!");
            } else {
                Auth.USER = nv;
                this.dispose();
                GiaoDienChinh gdc = new GiaoDienChinh();
                gdc.setVisible(true); 
            }
        }
          else if(ktuser.equalsIgnoreCase("SV")){
            SinhVien sv =  svDAO.selectByID(user);
            if(sv==null){
                 MsgBox.alert(this, "Sai tên đăng nhập!");
            }else if (!realPass.equals(sv.getMatKhau())) {
                MsgBox.alert(this, "Sai mật khẩu!");
            } else {
                String[] options = new String[2];
                options[0] = new String("Xem điểm");
                options[1] = new String("Vào thi");
//                int result = JOptionPane.showOptionDialog(this,"Bạn vào xem điểm hay thi","Xác nhận", 0,JOptionPane.INFORMATION_MESSAGE,null,options,null);
                String re=MsgBox.prompt(this, "");
                  if(re.equals("Xem điểm")){ 
                      Auth.USERSV = sv;
                        this.dispose();
                        BangDiemFrame gdc = new BangDiemFrame();
                        gdc.setVisible(true);
                  }else{
                        Auth.USERSV = sv;
                        this.dispose();
                        VaoThi gdc = new VaoThi();
                        gdc.setVisible(true);
                  }
                
            }
            
        }
    }
}
