/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.QLSV.Ui;

import com.QLSV.DAO.GiangVienDAO;
import com.QLSV.DAO.NhanVienDAO;
import com.QLSV.DAO.SinhVienDAO;
import com.QLSV.Utility.Auth;
import com.QLSV.Utility.MsgBox;
import java.awt.Color;
import static java.awt.Color.pink;
import static java.awt.Color.white;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author tontr
 */
public class DoiMatkhauPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoiMatkhauPanel
     */
    public DoiMatkhauPanel() {
        initComponents();checkUser();
    }
    NhanVienDAO nvdao = new NhanVienDAO();
    GiangVienDAO gvdao = new GiangVienDAO();
    
    public void doiMK(){
    if(Auth.isLogin()){
            doiMatKhauNV();
        }else if(Auth.isLoginGV()){
            doiMatKhauGV();
        }
    
    }
    public static boolean checkNullPass(JTextField txt) {
        txt.setBackground(white);
        if (txt.getText().toString().length() > 0) {
            return true;
        } else {
            txt.setBackground(pink);
            JOptionPane.showMessageDialog(txt.getRootPane(), "Không được để trống " + txt.getName());
            return false;
        }
    }

    
    public void doiMatKhauNV(){
        txtMatKhauCu.setBackground(Color.white);
        txtMatKhauMoi.setBackground(Color.white);
        txtNhapLai.setBackground(Color.white);
        String matKhau=new String(txtMatKhauCu.getText());
        String matKhauMoi=new String(txtMatKhauMoi.getText());
        String xacNhanMKM=new String(txtNhapLai.getText());
        if(matKhau.equals(Auth.USER.getMatKhau())){
            if(matKhauMoi.equals(xacNhanMKM)){
                Auth.USER.setMatKhau(matKhauMoi);
                nvdao.update(Auth.USER);
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!!");
            }else{
                txtNhapLai.setBackground(Color.pink);
                JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không trùng mật khẩu");
            }
        }else{
            txtMatKhauCu.setBackground(Color.pink);
            JOptionPane.showMessageDialog(this, "Mật khẩu cũ nhập không chính xác!");
        }
    }
    public void doiMatKhauGV(){
        txtMatKhauCu.setBackground(Color.white);
        txtMatKhauMoi.setBackground(Color.white);
        txtNhapLai.setBackground(Color.white);
        String matKhau=new String(txtMatKhauCu.getText());
        String matKhauMoi=new String(txtMatKhauMoi.getText());
        String xacNhanMKM=new String(txtNhapLai.getText());
        if(matKhau.equals(Auth.USERGV.getMatKhau())){
            if(matKhauMoi.equals(xacNhanMKM)){
                Auth.USERGV.setMatKhau(matKhauMoi);
                gvdao.update(Auth.USERGV);
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!!");
            }else{
                txtNhapLai.setBackground(Color.pink);
                JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không trùng mật khẩu");
            }
        }else{
            txtMatKhauCu.setBackground(Color.pink);
            JOptionPane.showMessageDialog(this, "Mật khẩu cũ nhập không chính xác!");
        }
    }
    String realPass = "";
    String matKhauChinh = null;
    void setPass(JTextField txt) {
        String matK = txt.getText();
        int len = matK.length();
        matKhauChinh = matK;
        int lenR = realPass.length();
            String sao = "";
            if (len > lenR) {
                String tam = matK.substring(lenR, len);
                realPass += tam;
            } else if (len < lenR) {
                realPass = realPass.substring(0, len);
            }
            for (int i = 0; i < realPass.length(); i++) {
                sao += "*";
            }
            txt.setText(sao);
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMatKhauCu = new javax.swing.JTextField();
        txtMatKhauMoi = new javax.swing.JTextField();
        txtNhapLai = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1180, 780));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/left_panel.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 31, 151));
        jLabel3.setText("ĐỔI MẬT KHẨU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Mật khẩu cũ :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Mật khẩu mới :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Nhập lại mật khẩu :");

        txtMatKhauCu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMatKhauCu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatKhauCuKeyReleased(evt);
            }
        });

        txtMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMatKhauMoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatKhauMoiKeyReleased(evt);
            }
        });

        txtNhapLai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNhapLai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNhapLaiKeyReleased(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/nutnhat.png"))); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSubmitMousePressed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/nutnhat.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNhapLai))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4))
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMatKhauCu)
                                        .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnSubmit)
                                .addGap(61, 61, 61)
                                .addComponent(btnCancel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel3)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnSubmit))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMousePressed

    }//GEN-LAST:event_btnSubmitMousePressed

    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
        setColor(btnSubmit);
    }//GEN-LAST:event_btnSubmitMouseEntered

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        resetColor(btnSubmit);
    }//GEN-LAST:event_btnSubmitMouseExited

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        setColor(btnCancel);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        resetColor(btnCancel);
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        // TODO add your handling code here:
        if(checkNullPass(txtMatKhauCu)&&
                checkNullPass(txtMatKhauMoi)&&
                checkNullPass(txtNhapLai)){
            doiMK();
        }
        
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void txtMatKhauCuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauCuKeyReleased
        // TODO add your handling code here:
//        setPass(txtMatKhauCu);
    }//GEN-LAST:event_txtMatKhauCuKeyReleased

    private void txtMatKhauMoiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauMoiKeyReleased
        // TODO add your handling code here:
//        setPass(txtMatKhauMoi);
    }//GEN-LAST:event_txtMatKhauMoiKeyReleased

    private void txtNhapLaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhapLaiKeyReleased
        // TODO add your handling code here:
//        setPass(txtNhapLai);
    }//GEN-LAST:event_txtNhapLaiKeyReleased
    void checkUser(){
        if(Auth.USER!=null){ 
            btnCancel.setEnabled(false);
        }else{
            btnCancel.setEnabled(true);
        }
    }
    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        if(Auth.USER!=null){ 
            return;
        }else{
            if(MsgBox.confirm(this, "Bạn muốn thoát không ?")){
                this.getParent().getParent().getParent().getParent().setVisible(false);
            }
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMouseClicked
    public void setColor(JLabel p) {
        p.setForeground(new Color(255, 250, 101));
    }

    public void resetColor(JLabel p1) {
        p1.setForeground(new Color(255, 255, 255));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMatKhauCu;
    private javax.swing.JTextField txtMatKhauMoi;
    private javax.swing.JTextField txtNhapLai;
    // End of variables declaration//GEN-END:variables
}
