/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLSV.Ui;


import com.QLSV.DAO.SinhVienDAO;
import com.QLSV.Model.SinhVien;
import com.QLSV.Utility.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

/**
 *
 * @author Tho
 */
public class LamTheSinhVienPanel extends javax.swing.JPanel {
    Double bHeight=0.0;
    SinhVienDAO dao=new SinhVienDAO();
    /**
     * Creates new form LamTheSinhVienPanel
     */
    public LamTheSinhVienPanel() throws IOException {
        initComponents();
//        fillTheSinhVien(dao.selectByID(txtMaSinhVien.getText()));
        JLabel background =new JLabel(new ImageIcon(getClass().getResource("/com/QLSV/Icon/TheSinhVie.png")));
        background.setBounds(1, 1, 820, 480);
        panelTheSinhVien.add(background);
    }
    public void fillTheSinhVien(SinhVien sv) throws IOException{
//        tenSinhVien.setBounds(180, 250, 500, 40);
        tenSinhVien.setFont(new Font("Tohama", Font.BOLD , 36));
        tenSinhVien.setText(sv.getTenSinhVien());
        
//        txtMaSV.setBounds(270, 260, 500, 40);
        txtMaSV.setFont(new Font("Tohama", Font.BOLD , 20));
        txtMaSV.setText(sv.getMaSinhVien());
        
//        txtNganh.setBounds(200, 300, 500, 40);
        txtNganh.setFont(new Font("Tohama", Font.BOLD , 22));
        txtNganh.setText(sv.getTenNganh());
        
        
//        txtHanSuDung.setBounds(230, 415, 500, 40);
        txtHanSuDung.setFont(new Font("Tohama", Font.BOLD , 15));
        int nam =Integer.parseInt(sv.getNgayNhapHoc().toString().substring(0,4));
        int thang =Integer.parseInt(sv.getNgayNhapHoc().toString().substring(5,7));
        nam+=2;
        txtHanSuDung.setText("Có giá trị đến T"+thang+"."+nam);

        try {
            ImageIcon avatar =new ImageIcon(getClass().getResource("/com/QLSV/Icon/"+sv.getAnhDaiDien()+".png"));
            Image ima=avatar.getImage();
            txtAnhDaiDien.setIcon(new ImageIcon(getScaledImage(ima, 150 , 150)));
        } catch (Exception e) {
            ImageIcon avatar =new ImageIcon(getClass().getResource("/com/QLSV/Icon/no.png"));
            Image ima=avatar.getImage();
            txtAnhDaiDien.setIcon(new ImageIcon(getScaledImage(ima, 150 , 150)));
        }
        
        
        txtAnhDaiDien.setBounds(600, 160, 150, 150);
        txtAnhDaiDien.setBackground(Color.red); 
        txtAnhDaiDien.setBorder(panelTheSinhVien.getBorder());
        
//        lblQR.setIcon(null);
        lblQR.setIcon(QR(sv));
        lblQR.setBounds(600, 310, 150, 150);
        lblQR.repaint();
        panelTheSinhVien.repaint();
    }
    private Image getScaledImage(Image srcImg, int w, int h){
        BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();

        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(srcImg, 0, 0, w, h, null);
        g2.dispose();

        return resizedImg;
    }
   
    public ImageIcon QR(SinhVien sv) throws FileNotFoundException, IOException{
        String details=sv.getTenSinhVien()+"\n"+sv.getMaSinhVien()+"\n"+sv.getCmnd()+"\n"+sv.getEmail()+"\n"+sv.getSoDienThoai()+"\n"+sv.getTenNganh();
        ByteArrayOutputStream out = QRCode.from(details).to(ImageType.PNG).stream();
        String Path=getClass().getResource("/bearwalk").getPath()+"/"+sv.getMaSinhVien()+".png";
        File f=new File(Path); 
        FileOutputStream fos=new FileOutputStream(f); 
        fos.write(out.toByteArray()); 
        fos.flush();  
        return new ImageIcon(Path); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JLabel();
        btnPrint = new javax.swing.JLabel();
        panelTheSinhVien = new javax.swing.JPanel();
        txtMaSV = new javax.swing.JLabel();
        tenSinhVien = new javax.swing.JLabel();
        txtNganh = new javax.swing.JLabel();
        txtHanSuDung = new javax.swing.JLabel();
        txtAnhDaiDien = new javax.swing.JLabel();
        lblQR = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Mã sinh viên :");

        txtMaSinhVien.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtMaSinhVien.setText("SV03");

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/nutTuGiacTB.png"))); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/nutTuGiac.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
        });

        panelTheSinhVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTheSinhVien.setPreferredSize(new java.awt.Dimension(822, 482));

        txtMaSV.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        tenSinhVien.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        txtNganh.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N

        txtHanSuDung.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtAnhDaiDien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAnhDaiDien.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panelTheSinhVienLayout = new javax.swing.GroupLayout(panelTheSinhVien);
        panelTheSinhVien.setLayout(panelTheSinhVienLayout);
        panelTheSinhVienLayout.setHorizontalGroup(
            panelTheSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTheSinhVienLayout.createSequentialGroup()
                .addGroup(panelTheSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTheSinhVienLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(tenSinhVien))
                    .addGroup(panelTheSinhVienLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(txtNganh))
                    .addGroup(panelTheSinhVienLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(txtMaSV))
                    .addGroup(panelTheSinhVienLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(txtHanSuDung)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addGroup(panelTheSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTheSinhVienLayout.createSequentialGroup()
                        .addComponent(txtAnhDaiDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTheSinhVienLayout.createSequentialGroup()
                        .addComponent(lblQR, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        panelTheSinhVienLayout.setVerticalGroup(
            panelTheSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTheSinhVienLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(tenSinhVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaSV)
                .addGap(18, 18, 18)
                .addComponent(txtNganh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtHanSuDung)
                .addGap(33, 33, 33))
            .addGroup(panelTheSinhVienLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(txtAnhDaiDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblQR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 31, 151));
        jLabel2.setText("LÀM THẺ SINH VIÊN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTheSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(82, 82, 82)
                                .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPrint))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(jLabel2)))
                .addGap(0, 157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(panelTheSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void thongTinSinhVien(){
        String maSV= txtMaSinhVien.getText();
        SinhVien sv=dao.selectByID(maSV);
        
    }
    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
        printTheSinhVien(panelTheSinhVien);
    }//GEN-LAST:event_btnPrintMouseClicked

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        try {
            fillTheSinhVien(dao.selectByID(txtMaSinhVien.getText()));
        } catch (Exception ex) {
            MsgBox.alert(this, "Không tìm thấy sinh viên");
        }
    }//GEN-LAST:event_btnSubmitMouseClicked
    private void printTheSinhVien(JPanel panel){
        PrinterJob printerJob =PrinterJob.getPrinterJob();
        printerJob.setJobName("Print abc");
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if(pageIndex >0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D =(Graphics2D)graphics;
                graphics2D.translate(pageFormat.getImageableX()*2   , pageFormat.getImageableY()*2);
                graphics2D.scale(0.5, 0.5);
                panel.paint(graphics2D);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult =printerJob.printDialog();
        if(returningResult){
            try {
                printerJob.print();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnPrint;
    private javax.swing.JLabel btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblQR;
    private javax.swing.JPanel panelTheSinhVien;
    private javax.swing.JLabel tenSinhVien;
    private javax.swing.JLabel txtAnhDaiDien;
    private javax.swing.JLabel txtHanSuDung;
    private javax.swing.JLabel txtMaSV;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JLabel txtNganh;
    // End of variables declaration//GEN-END:variables
}
