/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLSV.Ui;

import com.QLSV.DAO.DanhSachThiDAO;
import com.QLSV.DAO.DeDAO;
import com.QLSV.DAO.DiemDAO;
import com.QLSV.DAO.LichGiangDayDAO;
import com.QLSV.DAO.LopDAO;
import com.QLSV.DAO.SinhVienDAO;
import com.QLSV.Model.DanhSachThi;
import com.QLSV.Model.De;
import com.QLSV.Model.Diem;
import com.QLSV.Model.LichGiangDay;
import com.QLSV.Model.Lop;
import com.QLSV.Model.SinhVien;
import com.QLSV.Utility.Auth;
import com.QLSV.Utility.JdbcHelper;
import com.QLSV.Utility.MsgBox;
import com.QLSV.Utility.Other;
import com.QLSV.Utility.XImage;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tho
 */
public class LenDanhSachThiFrame extends javax.swing.JFrame {
    LichGiangDayDAO lgddao=new LichGiangDayDAO();
    /**
     * Creates new form LenDanhSachThi
     */
    public LenDanhSachThiFrame() throws SQLException {
        initComponents();
        Other.setTable(tblLop);
        Other.setTable(tblMonHoc);
        Other.setTable(tblDanhSachThi);
        getContentPane().setBackground(Color.white);
        loadCboLop();this.setIconImage(XImage.getAppIcon());
        loadTableLop();
    } 
    public void loadCboLop() throws SQLException{
       String sql ="select distinct malop from LichGiangDay where maGiangVien like ?";
       ResultSet rs=JdbcHelper.query(sql, Auth.USERGV.getMaGiangVien());
        cboLop.removeAllItems();
        while(rs.next()){
            cboLop.addItem(rs.getString(1)); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLop = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMonHoc = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cboLop = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboMonHoc = new javax.swing.JComboBox<>();
        btnNext1 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDanhSachThi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lên danh sách thi");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LÊN DANH SÁCH THI");

        tblLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "Điểm giữa kỳ", "Điểm cuối kỳ"
            }
        ));
        jScrollPane1.setViewportView(tblLop);

        tblMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã thi", "Kỳ thi", "Ngày mở ", "Ngày đóng", "Người tạo"
            }
        ));
        tblMonHoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblMonHoc);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Lớp :");

        cboLop.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLopActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Môn học :");

        cboMonHoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMonHocActionPerformed(evt);
            }
        });

        btnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/next.png"))); // NOI18N
        btnNext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNext1MouseClicked(evt);
            }
        });

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/rewind_120px.png"))); // NOI18N
        btnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack1MouseClicked(evt);
            }
        });

        tblDanhSachThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã đề ", "Mã sinh viên"
            }
        ));
        tblDanhSachThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachThiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDanhSachThi);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/DangXuat.png"))); // NOI18N
        jLabel4.setText("Tạo đề");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cboMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNext1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cboMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    DanhSachThiDAO dstdao =new DanhSachThiDAO();
    private void btnNext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext1MouseClicked
        try {
            String made = tblMonHoc.getValueAt(tblMonHoc.getSelectedRow(), 0).toString();
            String maMon =cboMonHoc.getSelectedItem().toString();     
            int rowC= tblLop.getSelectedRows().length;
            for (int i = 0; i < rowC; i++) {
                String masv=tblLop.getValueAt(tblLop.getSelectedRows()[i], 0).toString();
                dstdao.insert(new DanhSachThi(masv, made));
            }
            DefaultTableModel model =(DefaultTableModel )tblDanhSachThi.getModel();
            model.setRowCount(0);
            List<DanhSachThi> list=dstdao.selectAll();
            for (DanhSachThi danhSachThi : list) {
                model.addRow(new Object[]{danhSachThi.getMaDe(),danhSachThi.getMaSinhVien(),maMon,cboLop.getSelectedItem()});
            }
            loadTableDanhSachThi();
            loadTableLop();
        } catch (Exception e) {
            MsgBox.alert(this, "Vui lóng chọn thông tin thích hợp");
        }
        
    }//GEN-LAST:event_btnNext1MouseClicked
  void loadTableDanhSachThi() throws SQLException{
        DefaultTableModel model =(DefaultTableModel )tblDanhSachThi.getModel();
        model.setRowCount(0);
        List<DanhSachThi> list=dstdao.selectByMon(cboMonHoc.getSelectedItem().toString());
        System.out.println(list.size());
        for (DanhSachThi danhSachThi : list) {
            model.addRow(new Object[]{danhSachThi.getMaDe(),danhSachThi.getMaSinhVien()});
        }
        loadTableLop();
  }
    private void btnBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseClicked
        int rowC= tblDanhSachThi.getSelectedRows().length;
        for (int i = 0; i < rowC; i++) {
            String masv=tblDanhSachThi.getValueAt(tblDanhSachThi.getSelectedRows()[i], 1).toString();
            dstdao.delete((masv));
        }        
        try {
            loadTableDanhSachThi();
        } catch (SQLException ex) {
            Logger.getLogger(LenDanhSachThiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnBack1MouseClicked
    SinhVienDAO svdao=new SinhVienDAO();
    DiemDAO ddao=new DiemDAO();
    void loadTableLop(){
        try {
             List<Diem> list= ddao.selectSinhVien(cboMonHoc.getSelectedItem().toString(), cboLop.getSelectedItem().toString());
            DefaultTableModel model =(DefaultTableModel)tblLop.getModel();
            model.setRowCount(0);
            for (Diem sinhVien : list) {
                if(checkTrung(sinhVien.getMaSinhVien())==0){
                        model.addRow(new Object[]{sinhVien.getMaSinhVien(),sinhVien.getTenSV(), sinhVien.getDiemGiuaKi()==-1?"":sinhVien.getDiemGiuaKi(), sinhVien.getDiemCuoiKi()==-1?"":sinhVien.getDiemCuoiKi()}); 
                }
            }
        } catch (Exception e) {
        }
    }
    int checkTrung(String masv){
        for(int j =0;j<tblDanhSachThi.getRowCount();j++){
              if(masv.equals(tblDanhSachThi.getValueAt(j, 1))){
                  return 1;
              }  
            }
        return 0;
    }
    DeDAO dedao=new DeDAO();
    void loabTableDe(){
        List<De> list= dedao.selectByMonHoc(cboMonHoc.getSelectedItem().toString());
        DefaultTableModel model =(DefaultTableModel)tblMonHoc.getModel();
        model.setRowCount(0);
        for (De sinhVien : list) {
            model.addRow(new Object[]{sinhVien.getMaDe(),sinhVien.getKyThi(),sinhVien.getNgayMo(),sinhVien.getNgayDong(),sinhVien.getMaGiangVien()}); 
        }
    }
    private void cboLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLopActionPerformed
        if(cboLop.getItemCount()==0)        {
            return;
        }else{
            fillCboMon();
        }
    
    }//GEN-LAST:event_cboLopActionPerformed
    
    private void cboMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMonHocActionPerformed
        if(cboMonHoc.getItemCount()==0){
            return;
        }
        loabTableDe();try {
            loadTableDanhSachThi();
        } catch (SQLException ex) {
            Logger.getLogger(LenDanhSachThiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboMonHocActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        QuanLyDeFrame td=new QuanLyDeFrame();
        td.setVisible(true);          dispose();
      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void tblDanhSachThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachThiMouseClicked
       
    }//GEN-LAST:event_tblDanhSachThiMouseClicked
    LopDAO ldao=new LopDAO();
    void fillCboMon() {
        try {
            String lop = (String) cboLop.getSelectedItem();
            Lop lophoc = ldao.selectByID(lop);
            List<LichGiangDay> lich = lgddao.selectMon(Auth.USERGV.getMaGiangVien(), lop, lophoc.getMaky(), lophoc.getMaNganh());
            DefaultComboBoxModel cboModel = (DefaultComboBoxModel) cboMonHoc.getModel();
            cboModel.removeAllElements();
            for (LichGiangDay mon : lich) {
                cboModel.addElement(mon.getMaMon());
            }
        } catch (Exception e) {
            //MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            //e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LenDanhSachThiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LenDanhSachThiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LenDanhSachThiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LenDanhSachThiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LenDanhSachThiFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(LenDanhSachThiFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack1;
    private javax.swing.JLabel btnNext1;
    private javax.swing.JComboBox<String> cboLop;
    private javax.swing.JComboBox<String> cboMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDanhSachThi;
    private javax.swing.JTable tblLop;
    private javax.swing.JTable tblMonHoc;
    // End of variables declaration//GEN-END:variables
}
