/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLSV.Ui;

import com.QLSV.DAO.GiangVienDAO;
import com.QLSV.DAO.NganhDAO;
import com.QLSV.Model.GiangVien;
import com.QLSV.Utility.Auth;
import com.QLSV.Utility.MsgBox;
import com.QLSV.Utility.Other;
import com.QLSV.Utility.XImage;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Tho
 */
public class QuanLyGiangVienPanel extends javax.swing.JPanel {
    ArrayList<JPanel> list ;
    int trang;
    /**
     * Creates new form QuanLyGiangVienPanel
     */
    public QuanLyGiangVienPanel(ArrayList<JPanel> j,int i) {
        initComponents();
        Other.setTable(tblGiangVien);
        init();
        list=j;
        trang=i;
    }
    public void showPanel(int index){
        for (int i = 0; i < list.size(); i++) {
            list.get(i).show(false);
            if(i==index){
                list.get(index).show(true);
            }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GioiTinh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnMonGiangDay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaGiangVien = new javax.swing.JTextField();
        txtTenGiangVien = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboTrinhDo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboChuyenMon = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNgayVao = new com.toedter.calendar.JDateChooser();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGiangVien = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnNew = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnXoaAnh = new javax.swing.JButton();
        lblGV = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1180, 780));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 31, 151));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ GIẢNG VIÊN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 40, 786, -1));

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTimKiem.setBorder(null);
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });
        add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 387, 310, 20));

        btnMonGiangDay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMonGiangDay.setForeground(new java.awt.Color(255, 255, 255));
        btnMonGiangDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMonGiangDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/DangXuat.png"))); // NOI18N
        btnMonGiangDay.setText("Môn giảng dạy");
        btnMonGiangDay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMonGiangDay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMonGiangDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMonGiangDayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMonGiangDayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMonGiangDayMouseExited(evt);
            }
        });
        add(btnMonGiangDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 40, 196, 43));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mã giảng viên :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 107, 125, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Tên giảng viên :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 162, 125, -1));

        txtMaGiangVien.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtMaGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGiangVienActionPerformed(evt);
            }
        });
        add(txtMaGiangVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 105, 172, -1));

        txtTenGiangVien.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTenGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenGiangVienActionPerformed(evt);
            }
        });
        add(txtTenGiangVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 160, 200, -1));

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });
        add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 213, 200, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Số điện thoại :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 215, 106, -1));

        txtCMND.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });
        add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 265, 200, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("CMND/CCCD :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 267, 125, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 316, 200, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Email :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 318, 106, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Trình độ :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 107, -1, -1));

        cboTrinhDo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        cboTrinhDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thạc sĩ" }));
        add(cboTrinhDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 106, 200, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Chuyên môn :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 162, -1, -1));

        cboChuyenMon.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        cboChuyenMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "Photoshop", "Web" }));
        cboChuyenMon.setToolTipText("Thopro");
        cboChuyenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChuyenMonActionPerformed(evt);
            }
        });
        add(cboChuyenMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 161, 200, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Ngày vào :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 215, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Giới tính :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 318, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Ngày sinh :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 267, 84, -1));
        add(txtNgayVao, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 213, 200, 26));
        add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 265, 200, 26));

        rdoNam.setBackground(new java.awt.Color(255, 255, 255));
        GioiTinh.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 315, -1, -1));

        rdoNu.setBackground(new java.awt.Color(255, 255, 255));
        GioiTinh.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rdoNu.setText("Nữ");
        rdoNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuActionPerformed(evt);
            }
        });
        add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 315, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Địa chỉ :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 241, -1, -1));

        lblAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        lblAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhMouseClicked(evt);
            }
        });
        add(lblAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(978, 105, 114, 111));

        tblGiangVien.setAutoCreateRowSorter(true);
        tblGiangVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblGiangVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã GV", "Tên giảng viên", "Số điện thoại ", "CMND/CCCD", "Giới tính", "Trình độ", "Chuyên môn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGiangVien.setGridColor(new java.awt.Color(255, 255, 255));
        tblGiangVien.setRowHeight(20);
        tblGiangVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGiangVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGiangVien);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 427, 1020, 327));

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane3.setViewportView(txtDiaChi);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 241, 188, 103));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText("Ảnh đại diên :");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 107, -1, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/barSearch.png"))); // NOI18N
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 375, 465, -1));

        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/nutTuGiacTB.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewMouseExited(evt);
            }
        });
        add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 364, 120, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/nutTuGiacTB.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 364, 120, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/nutTuGiacTB.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 364, 120, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/nutTuGiacTB.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 364, 120, -1));

        btnXoaAnh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoaAnh.setText("Xóa ảnh");
        btnXoaAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaAnhActionPerformed(evt);
            }
        });
        add(btnXoaAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 162, -1, -1));

        lblGV.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblGV.setText("GV");
        add(lblGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 109, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGiangVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGiangVienActionPerformed

    private void txtTenGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenGiangVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenGiangVienActionPerformed

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void cboChuyenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChuyenMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChuyenMonActionPerformed

    private void rdoNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNuActionPerformed

    private void btnNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseEntered
        setColor(btnNew);
    }//GEN-LAST:event_btnNewMouseEntered

    private void btnNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseExited
        resetColor(btnNew);
    }//GEN-LAST:event_btnNewMouseExited

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        setColor(btnSave);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        resetColor(btnSave);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        setColor(btnUpdate);
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        resetColor(btnUpdate);
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        setColor(btnDelete);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        resetColor(btnDelete);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnMonGiangDayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonGiangDayMouseEntered
        setColor(btnMonGiangDay);
    }//GEN-LAST:event_btnMonGiangDayMouseEntered

    private void btnMonGiangDayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonGiangDayMouseExited
        resetColor(btnMonGiangDay);
    }//GEN-LAST:event_btnMonGiangDayMouseExited

    private void lblAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMouseClicked
        // TODO add your handling code here:
        chonAnh();
    }//GEN-LAST:event_lblAnhMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void tblGiangVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGiangVienMouseClicked
        lblAnh.setIcon(null);
        lblAnh.setToolTipText(null);
        row = tblGiangVien.getSelectedRow();
        edit();
        String magv = tblGiangVien.getValueAt(row, 0).toString();
        txtMaGiangVien.setText(magv.substring(2,magv.length()));
    }//GEN-LAST:event_tblGiangVienMouseClicked

    private void btnMonGiangDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonGiangDayMouseClicked
        showPanel(trang);        // TODO add your handling code here:
    }//GEN-LAST:event_btnMonGiangDayMouseClicked

    private void btnXoaAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaAnhActionPerformed
            // TODO add your handling code here:
        lblAnh.setIcon(null);
        lblAnh.setToolTipText(null);
    }//GEN-LAST:event_btnXoaAnhActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
          DefaultTableModel model = (DefaultTableModel)tblGiangVien.getModel();
        try {
            TableRowSorter<DefaultTableModel> ts = new TableRowSorter<>(model);
            tblGiangVien.setRowSorter(ts);
            ts.setRowFilter(RowFilter.regexFilter(txtTimKiem.getText()));
//            tblGridView.setRowSelectionInterval(0, 0);
        } catch (Exception e) {
        }   
    }//GEN-LAST:event_txtTimKiemKeyReleased

    public void setColor(JLabel p) {
        p.setForeground(new Color(255, 250, 101));
    }

    public void resetColor(JLabel p1) {
        p1.setForeground(new Color(255, 255, 255));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GioiTinh;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnMonGiangDay;
    private javax.swing.JLabel btnNew;
    private javax.swing.JLabel btnSave;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JButton btnXoaAnh;
    private javax.swing.JComboBox<String> cboChuyenMon;
    private javax.swing.JComboBox<String> cboTrinhDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblGV;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblGiangVien;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaGiangVien;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private com.toedter.calendar.JDateChooser txtNgayVao;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenGiangVien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
   public void init() {
        this.fillTable();
        this.row=-1;
//        this.updateStatus();
        lblAnh.setBounds(lblAnh.getX(),lblAnh.getY(), 166, 216);
//        if(!Auth.isLogin()){
//            MsgBox.alert(this, "Bạn chưa đăng nhập!");
//            System.exit(0);
//        }
        txtNgayVao.setDateFormatString("dd-MM-yyyy");
        txtNgaySinh.setDateFormatString("dd-MM-yyyy");
        tblGiangVien.getTableHeader().setBackground(Color.BLACK);
        //fillComboBox();
    }
    DefaultTableModel model;
    GiangVienDAO dao = new GiangVienDAO();
    int row = -1;
    NganhDAO ndao = new NganhDAO();
    
//    void fillComboBox(){
//        DefaultComboBoxModel cbomodel = (DefaultComboBoxModel) cboChuyenMon.getModel();
//        cbomodel.removeAllElements();
//        List<Nganh> list = ndao.selectAll();
//        for(Nganh c: list){
//            cbomodel.addElement(c.getTenNganh());
//        }
//    }
    
    void fillTable(){
        model = (DefaultTableModel) tblGiangVien.getModel();
        model.setRowCount(0);
        try {
            List<GiangVien> list=null;
                list = dao.selectAll();
            
            for(GiangVien cd : list){
                Object row[] = {cd.getMaGiangVien(), cd.getTenGiangVien(),cd.getSoDienThoai(), cd.getCmnd(), cd.isGioiTinh()?"Nam":"Nữ",
            cd.getTrinhDo(),cd.getChuyenMon()};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
   
    
    void setForm(GiangVien cd){
        txtMaGiangVien.setText(cd.getMaGiangVien());
        //txtPassword.setText(cd.getMatKhau());
        txtCMND.setText(cd.getCmnd());
        txtDiaChi.setText(cd.getDiaChi());
        txtEmail.setText(cd.getEmail());
        txtNgaySinh.setDate(cd.getNgaySinh());
        txtNgayVao.setDate(cd.getNgayVao());
        txtSoDienThoai.setText(cd.getSoDienThoai());
        txtTenGiangVien.setText(cd.getTenGiangVien());
        rdoNam.setSelected(cd.isGioiTinh());
        rdoNu.setSelected(!cd.isGioiTinh());
        cboChuyenMon.setSelectedItem(cd.getChuyenMon());
        cboTrinhDo.setSelectedItem(cd.getTrinhDo());
        try {
            if(!cd.getAnhDaiDien().equals("")||cd.getAnhDaiDien()!=null){
                    lblAnh.setToolTipText(cd.getAnhDaiDien());
                    lblAnh.setIcon(XImage.readLogo(cd.getAnhDaiDien()));

            }else{
                lblAnh.setIcon(null);
            }
        } catch (Exception e) {
        }
        
    }
    
    void clearForm(){
        GiangVien cd = new GiangVien();
        this.setForm(cd);
        this.row = -1;
//        this.updateStatus();
        cboChuyenMon.setSelectedIndex(0);
        cboTrinhDo.setSelectedIndex(0);
        //lblAnh.setIcon(new ImageIcon(getClass().getResource("/imageTest/iconMayAnh_pts.png")));
        lblAnh.setIcon(null);
        tblGiangVien.clearSelection();
        lblAnh.setToolTipText(null);
    }
    
//    void updateStatus(){
//        boolean edit = (this.row>=0);
//        boolean first = (this.row==0);
//        boolean last = (this.row==tblGiangVien.getRowCount()-1);
//        txtMaGiangVien.setEditable(!edit);
//        //txtPassword.setEnabled(false);
//        btnSave.setEnabled(!edit);
//        btnDelete.setEnabled(edit);
//        btnUpdate.setEnabled(edit);
////        btnFirst.setEnabled(edit&&!first);
////        btnPrev.setEnabled(edit&&!first);
////        btnLast.setEnabled(edit&&!last);
////        btnNext.setEnabled(edit&&!last);
//    }
    
    void edit(){
        try {
            String manv =  tblGiangVien.getValueAt(this.row, 0).toString();
            GiangVien nv = dao.selectByID(manv);
            this.setForm(nv);
        } catch (Exception e) {
        }
        
//        this.updateStatus();
    }
     GiangVien getForm(){
        GiangVien cd = new GiangVien();
        cd.setAnhDaiDien(lblAnh.getToolTipText());
        cd.setChuyenMon((String) cboChuyenMon.getSelectedItem());
        cd.setCmnd(txtCMND.getText());
        cd.setDiaChi(txtDiaChi.getText());
        cd.setEmail(txtEmail.getText());
        cd.setGioiTinh(rdoNam.isSelected());
        cd.setMaGiangVien("GV"+txtMaGiangVien.getText());
        cd.setMatKhau("1");
        cd.setNgaySinh(new java.sql.Date(txtNgaySinh.getDate().getTime()));
        cd.setNgayVao(new java.sql.Date(txtNgayVao.getDate().getTime()));
        cd.setTenGiangVien(txtTenGiangVien.getText());
        cd.setSoDienThoai(txtSoDienThoai.getText());
        cd.setTrinhDo((String) cboTrinhDo.getSelectedItem());
        cd.setManv(Auth.USER.getMaNV());
        return cd;
    }
    void insert(){
        if(fixform()==false){
            return;
        }
        GiangVien nv = getForm();
        try {
            dao.insert(nv);
            this.fillTable();
            this.clearForm();         
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
            e.printStackTrace();
        }
    }
    
    void update(){
        if(fixformUpdate()==false){
            return;
        }
        GiangVien nv = getForm();
        try {
            dao.update(nv);
            this.fillTable();
            this.clearForm();         
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
            e.printStackTrace();
        }
    }
    
    void delete(){
        if(!Auth.isManager()){
            MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này");
        }else{
            String manv = "GV"+txtMaGiangVien.getText();
            if(MsgBox.confirm(this, "Bạn có thực sữ muốn xóa giảng viên này này!")){
                try {
                    dao.delete(manv);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại!");
                }
            }
        }
    }
    
    void first(){
        this.row = 0;
        this.edit();
    }
    
    void next(){
        if (this.row <tblGiangVien.getRowCount()-1) {
            this.row++;
            this.edit();
        }
    }
    
    void prev(){
        if(this.row >0){
            this.row--;
            this.edit();
        }
    }
    
    void last(){
        this.row=tblGiangVien.getRowCount()-1;
        this.edit();
    }    
    
    boolean fixform(){
        int tong = tblGiangVien.getRowCount();
        String magv = "GV"+txtMaGiangVien.getText();
        if(magv.equals("")){
            MsgBox.alert(this,"Không được bỏ trống mã giảng viên!");
            return false;
        }
        if(txtTenGiangVien.getText().equalsIgnoreCase("")){
            MsgBox.alert(this,"Không được bỏ trống tên giảng viên!");
            return false;
        }
        if(txtSoDienThoai.getText().equalsIgnoreCase("")){
            MsgBox.alert(this,"Không được bỏ trống số điện thoại!");
            return false;
        }
        if(txtCMND.getText().equalsIgnoreCase("")){
            MsgBox.alert(this,"Không được bỏ trống CMND!");
            return false;
        }
        if(txtEmail.getText().equalsIgnoreCase("")){
            MsgBox.alert(this,"Không được bỏ trống Email!");
            return false;
        }
        if(txtDiaChi.getText().equalsIgnoreCase("")){
            MsgBox.alert(this,"Không được bỏ trống địa chỉ!");
            return false;
        }
        if(txtNgaySinh.getDate()==(null)){
            MsgBox.alert(this,"Không được bỏ trống ngày sinh!");
            return false;
        }
        if(txtNgayVao.getDate()==(null)){
            MsgBox.alert(this,"Không được bỏ trống ngày vào!");
            return false;
        }
        try {
             Long.parseLong(txtSoDienThoai.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "Số điện thoại phải được nhập bằng số");
            return false;
        }
        try {
             Long.parseLong(txtCMND.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "CMND phải được nhập bằng số");
            return false;
        }
        String checkmail = "\\w+@\\w+(\\.\\w+){1,2}";
        try {
            if(!txtEmail.getText().matches(checkmail)){
                MsgBox.alert(this, "Không nhập đúng định dạng email (abc@xyz .123)!");
                return false;
            }
        } catch (Exception e) {
        }
        for(int i=0;i<tong;i++){
            if(magv.equalsIgnoreCase(tblGiangVien.getValueAt(i, 0).toString())){
                MsgBox.alert(this,"Mã giảng viên đã tồn tại!");
                return false;
            }
            if(txtSoDienThoai.getText().equalsIgnoreCase(tblGiangVien.getValueAt(i, 2).toString())){
                MsgBox.alert(this,"Số điện thoại đã tồn tại!");
                return false;
            }
            if(txtCMND.getText().equalsIgnoreCase(tblGiangVien.getValueAt(i, 3).toString())){
                MsgBox.alert(this,"CMND đã tồn tại!");
                return false;
            }
            if(txtEmail.getText().equalsIgnoreCase(tblGiangVien.getValueAt(i, 4).toString())){
                MsgBox.alert(this,"Email đã tồn tại!");
                return false;
            }
        }
        return true;
    }
//    
    boolean fixformUpdate(){
      int tong = tblGiangVien.getRowCount();
        if(txtTenGiangVien.getText().equalsIgnoreCase("")){
            MsgBox.alert(this,"Không được bỏ trống tên giảng viên!");
            return false;
        }
        if(txtSoDienThoai.getText().equalsIgnoreCase("")){
            MsgBox.alert(this,"Không được bỏ trống số điện thoại!");
            return false;
        }
        if(txtCMND.getText().equalsIgnoreCase("")){
            MsgBox.alert(this,"Không được bỏ trống CMND!");
            return false;
        }
        if(txtEmail.getText().equalsIgnoreCase("")){
            MsgBox.alert(this,"Không được bỏ trống Email!");
            return false;
        }
        if(txtDiaChi.getText().equalsIgnoreCase("")){
            MsgBox.alert(this,"Không được bỏ trống địa chỉ!");
            return false;
        }
        if(txtNgaySinh.getDate()==(null)){
            MsgBox.alert(this,"Không được bỏ trống ngày sinh!");
            return false;
        }
        if(txtNgayVao.getDate()==(null)){
            MsgBox.alert(this,"Không được bỏ trống ngày vào!");
            return false;
        }
        try {
             Long.parseLong(txtSoDienThoai.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "Số điện thoại phải được nhập bằng số");
            return false;
        }
        try {
             Long.parseLong(txtCMND.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "CMND phải được nhập bằng số");
            return false;
        }
        String checkmail = "\\w+@\\w+(\\.\\w+){1,2}";
        try {
            if(!txtEmail.getText().matches(checkmail)){
                MsgBox.alert(this, "Không nhập đúng định dạng email (abc@xyz .123)!");
                return false;
            }
        } catch (Exception e) {
        }
        int checktrung = -1 ;
        String magv = "GV"+txtMaGiangVien.getText();
        for(int i=0;i<tong;i++){
            if(magv.equalsIgnoreCase(tblGiangVien.getValueAt(i, 0).toString())){
                checktrung =i;
                break;
            }
            if((i==tong-1)&&(!magv.equalsIgnoreCase(tblGiangVien.getValueAt(i, 0).toString()))){
                MsgBox.alert(this,"Mã giảng viên không tồn tại!");
                return false;
            }
        }
        for(int i=0;i<tong;i++){
        if((txtSoDienThoai.getText().equalsIgnoreCase(tblGiangVien.getValueAt(i, 2).toString()))&&(checktrung!=i)){
                MsgBox.alert(this,"Số điện thoại đã tồn tại!");
                return false;
            }
            if((txtCMND.getText().equalsIgnoreCase(tblGiangVien.getValueAt(i, 3).toString()))&&(checktrung!=i)){
                MsgBox.alert(this,"CMND đã tồn tại!");
                return false;
            }
            if((txtEmail.getText().equalsIgnoreCase(tblGiangVien.getValueAt(i, 4).toString()))&&(checktrung!=i)){
                MsgBox.alert(this,"Email đã tồn tại!");
                return false;
            }
        }
        return true;
    }
    
    JFileChooser fileChooser = new JFileChooser();
    

    
     void chonAnh(){
        JFileChooser fileChooser= new JFileChooser();
        if(fileChooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            XImage.saveLogo(file);
            ImageIcon icon = XImage.readLogo(file.getName());
            lblAnh.setIcon(new ImageIcon(fileChooser.getCurrentDirectory()+"/"+file.getName()));
            lblAnh.setToolTipText(file.getName());
        }
    }
}
