/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.QLSV.Ui;

import com.QLSV.DAO.DiemDAO;
import com.QLSV.DAO.LopDAO;
import com.QLSV.DAO.LopSinhVienDAO;
import com.QLSV.DAO.MonHocCuaNganhDAO;
import com.QLSV.DAO.MonHocDAO;
import com.QLSV.DAO.NganhDAO;
import com.QLSV.DAO.SinhVienDAO;
import com.QLSV.Model.Lop;
import com.QLSV.Model.MonHoc;
import com.QLSV.Model.Nganh;
import com.QLSV.Model.LopSinhVien;
import com.QLSV.Model.SinhVien;
import com.QLSV.Model.MonHocCuaNganh;
import com.QLSV.Utility.MsgBox;
import com.QLSV.Utility.Other;
import java.awt.Color;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tontr
 */
public class SinhVienRotMonPanel extends javax.swing.JPanel {

    /**
     * Creates new form SinhVienRotMonPanel
     */
    public SinhVienRotMonPanel() {
        initComponents();
        Other.setTable(tblLeft);
        Other.setTable(tblRight);
        loadCboNganh();
        cboMon.removeAllItems(); 
        cboLop.removeAllItems();

    }
    DiemDAO ddao=new DiemDAO();
    NganhDAO ndao =new NganhDAO();
    MonHocDAO mhdao=new MonHocDAO() ;
    LopDAO ldao=new LopDAO();
    MonHocCuaNganhDAO mhcndao =new MonHocCuaNganhDAO();
    SinhVienDAO svdao=new SinhVienDAO();
    LopSinhVienDAO lsvdao=new LopSinhVienDAO();
    void loadCboNganh(){
        List<Nganh> n =ndao.selectAll();
        cboNganh.removeAllItems();
        for (Nganh nganh : n) {
            cboNganh.addItem(nganh.getMaNganh()+ " - "+nganh.getTenNganh());
        } 
    }
    void loadCboKy(){
        cboKy.removeAllItems();
        String maNganh =cboNganh.getSelectedItem().toString().substring(0,cboNganh.getSelectedItem().toString().indexOf(" "));
        List<MonHocCuaNganh> list= mhcndao.cboThem(maNganh) ;
        for (MonHocCuaNganh monHocCuaNganh : list) {
            cboKy.addItem(String.valueOf(monHocCuaNganh.getMaky()));
        }
        
    }
    void loadCboMon(){
        String maNganh =cboNganh.getSelectedItem().toString().substring(0,cboNganh.getSelectedItem().toString().indexOf(" "));
        List<MonHoc> mh =mhdao.cboThem(Integer.parseInt(cboKy.getSelectedItem().toString()),maNganh );
        cboMon.removeAllItems();
        for (MonHoc monHoc : mh) {
            cboMon.addItem(monHoc.getMaMon()+" - "+monHoc.getTenMon());
        }
    }
    void loadCboLop(){
        String maNganh =cboNganh.getSelectedItem().toString().substring(0,cboNganh.getSelectedItem().toString().indexOf(" "));
        List<Lop> mh =ldao.cboThem(maNganh,Integer.parseInt(cboKy.getSelectedItem().toString()) );
        cboLop.removeAllItems();
        for (Lop monHoc : mh) {
            cboLop.addItem(monHoc.getMaLop());
        }
    }
    void loadTblRight(){
        DefaultTableModel model =(DefaultTableModel)tblRight.getModel();
        model.setRowCount(0);
        List<SinhVien> list =svdao.tblRight(cboLop.getSelectedItem().toString());
        for (SinhVien sinhVien : list) {
            model.addRow(new Object[]{sinhVien.getMaSinhVien(),sinhVien.getTenSinhVien(),sinhVien.getCmnd()});
        }
    }
    void loadTblLeft(){
        String maNganh =cboNganh.getSelectedItem().toString().substring(cboNganh.getSelectedItem().toString().lastIndexOf(" - ")+3,cboNganh.getSelectedItem().toString().length());
        String maMon =cboMon.getSelectedItem().toString().substring(0,cboMon.getSelectedItem().toString().indexOf(" "));
        DefaultTableModel model =(DefaultTableModel)tblLeft.getModel();
        model.setRowCount(0);
        List<SinhVien> list =svdao.FillTblLeft(maNganh,maMon);
        for (SinhVien sinhVien : list) {
            model.addRow(new Object[]{sinhVien.getMaSinhVien(),sinhVien.getTenSinhVien(),sinhVien.getCmnd()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLeft = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRight = new javax.swing.JTable();
        cboNganh = new javax.swing.JComboBox<>();
        cboKy = new javax.swing.JComboBox<>();
        cboMon = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        cboLop = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1180, 780));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 31, 151));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SINH VIÊN RỚT MÔN HỌC LẠI");

        tblLeft.setAutoCreateRowSorter(true);
        tblLeft.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblLeft.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "CMND"
            }
        ));
        tblLeft.setGridColor(new java.awt.Color(255, 255, 255));
        tblLeft.setRowHeight(20);
        jScrollPane1.setViewportView(tblLeft);

        tblRight.setAutoCreateRowSorter(true);
        tblRight.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblRight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "CMND"
            }
        ));
        tblRight.setGridColor(new java.awt.Color(255, 255, 255));
        tblRight.setRowHeight(20);
        jScrollPane2.setViewportView(tblRight);

        cboNganh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cboNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNganhActionPerformed(evt);
            }
        });

        cboKy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cboKy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKyActionPerformed(evt);
            }
        });

        cboMon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cboMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã môn:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Kỳ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nghành :");

        btnNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/next.png"))); // NOI18N
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/rewind_120px.png"))); // NOI18N
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        cboLop.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cboLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLopActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Mã lớp :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cboKy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnNext))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboMon, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNganhActionPerformed
        if(cboNganh.getItemCount()==0){
            return;
        }
        loadCboKy();
// TODO add your handling code here:
    }//GEN-LAST:event_cboNganhActionPerformed

    private void cboKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKyActionPerformed
        if(cboKy.getItemCount()==0){
            return;
        }
        clearTableRight();
        loadCboMon();loadCboLop();
    }//GEN-LAST:event_cboKyActionPerformed

    private void cboLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLopActionPerformed
         if(cboLop.getItemCount()==0){
            return;
        }
        clearTableRight();
        loadTblRight();           // TODO add your handling code here:
    }//GEN-LAST:event_cboLopActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        if(cboLop.getItemCount()==0){
            MsgBox.alert(this, "Chưa có lớp !");
            return;
        }
        int row[]=tblLeft.getSelectedRows();
        int soLan= row.length;
        for (int i = 0; i < soLan; i++) {
            String maSV =tblLeft.getValueAt(row[i], 0).toString();
            String maMon =cboMon.getSelectedItem().toString().substring(0,cboMon.getSelectedItem().toString().indexOf(" "));
            ddao.themSV(maSV,maMon);
            lsvdao.insert(new LopSinhVien( maSV, cboLop.getSelectedItem().toString()));
        }
        loadTblRight();
        loadTblLeft();

    }//GEN-LAST:event_btnNextMouseClicked

    private void cboMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMonActionPerformed
        if(cboMon.getItemCount()==0){
            return;
        }
        clearTableLeft();
        loadTblLeft();        // TODO add your handling code here:
    }//GEN-LAST:event_cboMonActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        
        int row[]=tblRight.getSelectedRows();
        int soLan= row.length;
        for (int i = 0; i < soLan; i++) {
            String maSV =tblRight.getValueAt(row[i], 0).toString();
            String maMon =cboMon.getSelectedItem().toString().substring(0,cboMon.getSelectedItem().toString().indexOf(" "));
            lsvdao.delete(cboLop.getSelectedItem().toString(), maSV );
            ddao.updateOutLop(maSV,maMon);
        }
        loadTblLeft();
        loadTblRight();
        
    }//GEN-LAST:event_btnBackMouseClicked
    void clearTableRight(){
        DefaultTableModel model =(DefaultTableModel)tblRight.getModel();
        model.setRowCount(0);
    }
    void clearTableLeft(){
        DefaultTableModel model1 =(DefaultTableModel)tblLeft.getModel();
        model1.setRowCount(0);
    }
    public void setColor(JLabel p){
        p.setForeground(new Color(255, 250, 101));
    }
    public void resetColor(JLabel p1){
        p1.setForeground(new Color(255, 255, 255));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnNext;
    private javax.swing.JComboBox<String> cboKy;
    private javax.swing.JComboBox<String> cboLop;
    private javax.swing.JComboBox<String> cboMon;
    private javax.swing.JComboBox<String> cboNganh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblLeft;
    private javax.swing.JTable tblRight;
    // End of variables declaration//GEN-END:variables
}
