/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLSV.Ui;

/**
 *
 * @author Tho
 */
public class ThemSinhVienPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ThemSinhVienPanel
     */
    public ThemSinhVienPanel() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNhapHoc = new javax.swing.JLabel();
        btnRotMon = new javax.swing.JLabel();
        btnChinh = new javax.swing.JPanel();
        panelRotMon = new com.QLSV.Ui.SinhVienRotMonPanel();
        panelNhapHoc = new com.QLSV.Ui.ThemSinhVienVaoLopPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnNhapHoc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNhapHoc.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/nutTuGiacDai.png"))); // NOI18N
        btnNhapHoc.setText("Nhập học");
        btnNhapHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapHoc.setFocusable(false);
        btnNhapHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhapHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapHocMouseClicked(evt);
            }
        });

        btnRotMon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRotMon.setForeground(new java.awt.Color(255, 255, 255));
        btnRotMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/nutTuGiacDai.png"))); // NOI18N
        btnRotMon.setText("Rớt môn");
        btnRotMon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRotMon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRotMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRotMonMouseClicked(evt);
            }
        });

        btnChinh.setLayout(new java.awt.CardLayout());
        btnChinh.add(panelRotMon, "card2");
        btnChinh.add(panelNhapHoc, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnNhapHoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRotMon)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnChinh, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapHoc)
                    .addComponent(btnRotMon))
                .addGap(0, 0, 0)
                .addComponent(btnChinh, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRotMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRotMonMouseClicked
        panelNhapHoc.show(false);
        panelRotMon.show(true);
    }//GEN-LAST:event_btnRotMonMouseClicked

    private void btnNhapHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapHocMouseClicked
        panelNhapHoc.show(true);
        panelRotMon.show(false);
    }//GEN-LAST:event_btnNhapHocMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnChinh;
    private javax.swing.JLabel btnNhapHoc;
    private javax.swing.JLabel btnRotMon;
    private com.QLSV.Ui.ThemSinhVienVaoLopPanel panelNhapHoc;
    private com.QLSV.Ui.SinhVienRotMonPanel panelRotMon;
    // End of variables declaration//GEN-END:variables
}
