/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.QLSV.Ui;

import com.QLSV.DAO.DiemDAO;
import com.QLSV.DAO.LopDAO;
import com.QLSV.DAO.LopSinhVienDAO;
import com.QLSV.DAO.MonHocCuaNganhDAO;
import com.QLSV.DAO.MonHocDAO;
import com.QLSV.DAO.NganhDAO;
import com.QLSV.DAO.SinhVienDAO;
import com.QLSV.Model.Lop;
import com.QLSV.Model.Nganh;
import com.QLSV.Model.LopSinhVien;
import com.QLSV.Model.MonHocCuaNganh;
import com.QLSV.Model.SinhVien;
import com.QLSV.Utility.MsgBox;
import com.QLSV.Utility.Other;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tontr
 */
public class ThemSinhVienVaoLopPanel extends javax.swing.JPanel {
    DiemDAO ddao=new DiemDAO();
    NganhDAO ndao =new NganhDAO();
    MonHocDAO mhdao=new MonHocDAO() ;
    LopDAO ldao=new LopDAO();
    MonHocCuaNganhDAO mhcndao =new MonHocCuaNganhDAO();
    SinhVienDAO svdao=new SinhVienDAO();
    LopSinhVienDAO lsvdao=new LopSinhVienDAO();
    /**
     * Creates new form ThemSinhVienVaoLopPanel
     */
    public ThemSinhVienVaoLopPanel() {
        initComponents();
        loadCboNganh();
        Other.setTable(tblLeft);
        Other.setTable(tblRight);
        cboMaLop.removeAllItems();
    }
    void loadCboNganh(){
        List<Nganh> n =ndao.selectAll();
        cboNganh.removeAllItems();
        for (Nganh nganh : n) {
            cboNganh.addItem(nganh.getMaNganh()+ " - "+nganh.getTenNganh());
        } 
    }
    void loadCboKy(){
        cboKy.removeAllItems();
        String maNganh =cboNganh.getSelectedItem().toString().substring(0,cboNganh.getSelectedItem().toString().indexOf(" "));
        List<MonHocCuaNganh> list= mhcndao.cboThem(maNganh) ;
        for (MonHocCuaNganh monHocCuaNganh : list) {
            cboKy.addItem(String.valueOf(monHocCuaNganh.getMaky()));
        }
        
    }
    void loadCboLop(){
        String maNganh =cboNganh.getSelectedItem().toString().substring(0,cboNganh.getSelectedItem().toString().indexOf(" "));
        List<Lop> mh =ldao.cboThem(maNganh,Integer.parseInt(cboKy.getSelectedItem().toString()) );
        cboMaLop.removeAllItems();
        for (Lop monHoc : mh) {
            cboMaLop.addItem(monHoc.getMaLop());
        }
    }
    void loadTblLeft(){
        String tenNganh =cboNganh.getSelectedItem().toString().substring(cboNganh.getSelectedItem().toString().lastIndexOf(" - ")+3,cboNganh.getSelectedItem().toString().length());
        DefaultTableModel model =(DefaultTableModel)tblLeft.getModel();
        model.setRowCount(0);
        List<SinhVien> list =svdao.svMoi(tenNganh);
        for (SinhVien sinhVien : list) {
            model.addRow(new Object[]{sinhVien.getMaSinhVien(),sinhVien.getTenSinhVien(),sinhVien.getCmnd()});
        }
    }
    void loadTblRight(){
        DefaultTableModel model =(DefaultTableModel)tblRight.getModel();
        model.setRowCount(0);
        List<SinhVien> list =svdao.tblRight(cboMaLop.getSelectedItem().toString());
        for (SinhVien sinhVien : list) {
            model.addRow(new Object[]{sinhVien.getMaSinhVien(),sinhVien.getTenSinhVien(),sinhVien.getCmnd()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLeft = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRight = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cboMaLop = new javax.swing.JComboBox<>();
        btnNext1 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboNganh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboKy = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1172, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1172, 710));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 66, 250));
        jLabel4.setText("THÊM SINH VIÊN VÀO LỚP");

        tblLeft.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblLeft.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "CMND"
            }
        ));
        jScrollPane3.setViewportView(tblLeft);

        tblRight.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblRight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "CMND"
            }
        ));
        jScrollPane4.setViewportView(tblRight);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Mã lớp :");

        cboMaLop.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboMaLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/next.png"))); // NOI18N
        btnNext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNext1MouseClicked(evt);
            }
        });

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLSV/Icon/rewind_120px.png"))); // NOI18N
        btnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mã ngành :");

        cboNganh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNganhActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Kỳ");

        cboKy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cboKy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cboKy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNext1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addComponent(cboMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(cboMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(49, Short.MAX_VALUE))))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Mã lớp :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cboKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKyActionPerformed
        if(cboKy.getItemCount()==0){
            return;
        }
        cboMaLop.removeAllItems();
        clearTableLeft();clearTableRight();
        if(Integer.parseInt(cboKy.getSelectedItem().toString())==1){
            loadTblLeft();
        }
        
        loadCboLop(); 
    }//GEN-LAST:event_cboKyActionPerformed

    private void cboNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNganhActionPerformed
        if(cboNganh.getItemCount()==0){
            return;
        }
        clearTableLeft();clearTableRight();
        loadCboKy();
        if(cboMaLop.getItemCount()==0){
            return;
        }
        loadTblRight();
              // TODO add your handling code here:
    }//GEN-LAST:event_cboNganhActionPerformed

    private void btnNext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext1MouseClicked
        if(cboMaLop.getItemCount()==0){
            MsgBox.alert(this, "Chưa có lớp !");
            return;
        }
        int row[]=tblLeft.getSelectedRows();
        int soLan= row.length;
        for (int i = 0; i < soLan; i++) {
            String maSV =tblLeft.getValueAt(row[i], 0).toString();
            lsvdao.insert(new LopSinhVien( maSV, cboMaLop.getSelectedItem().toString()));
        }
        loadTblRight();
        loadTblLeft();        // TODO add your handling code here:
    }//GEN-LAST:event_btnNext1MouseClicked

    private void btnBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseClicked
        int row[]=tblRight.getSelectedRows();
        int soLan= row.length;
        for (int i = 0; i < soLan; i++) {
            String maSV =tblRight.getValueAt(row[i], 0).toString();
            lsvdao.delete(cboMaLop.getSelectedItem().toString(), maSV );
        }
        loadTblLeft();
        loadTblRight();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack1;
    private javax.swing.JLabel btnNext1;
    private javax.swing.JComboBox<String> cboKy;
    private javax.swing.JComboBox<String> cboMaLop;
    private javax.swing.JComboBox<String> cboNganh;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblLeft;
    private javax.swing.JTable tblRight;
    // End of variables declaration//GEN-END:variables
    void clearTableRight(){
        DefaultTableModel model =(DefaultTableModel)tblRight.getModel();
        model.setRowCount(0);
    }
    void clearTableLeft(){
        DefaultTableModel model1 =(DefaultTableModel)tblLeft.getModel();
        model1.setRowCount(0);
    }
}
