/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLSV.Ui;

import com.QLSV.DAO.CauHoiDAO;
import com.QLSV.DAO.DapAnDAO;
import com.QLSV.DAO.DeDAO;
import com.QLSV.DAO.DiemDAO;
import com.QLSV.DAO.SinhVienDAO;
import com.QLSV.Model.CauHoi;
import com.QLSV.Model.De;
import com.QLSV.Model.SinhVien;
import com.QLSV.Utility.JdbcHelper;
import com.QLSV.Utility.MsgBox;
import com.QLSV.Utility.XImage;
import java.awt.Color;
import java.io.IOException;
import java.net.MalformedURLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Tho
 */
public class ThiFrame extends javax.swing.JFrame {
    int thoigian=0;
    int giay=00;
    DeDAO ddao =new DeDAO();
    CauHoiDAO chdao= new CauHoiDAO()    ;
    DapAnDAO dadao=new DapAnDAO();
    int soLuong=0;
    ArrayList<CauHoi> listCH =new ArrayList<CauHoi>();
    ArrayList<CauHoiPanel> listPanel =new ArrayList<CauHoiPanel>();
    ArrayList<TabButton> listButton =new ArrayList<TabButton>();

    SinhVienDAO svdao=new SinhVienDAO();
    /**
     * Creates new form ThiFrame
     */
    public ThiFrame(String maDe ,String maSV) {
        initComponents();
        this.getContentPane().setBackground(new Color(245,245,245));
        fillThongTin(maDe, maSV);this.setIconImage(XImage.getAppIcon());
    }
    void fillThongTin(String maDe ,String maSV){
        SinhVien sv=svdao.selectByID(maSV);
        lblMaSinhVien.setText(maSV);
        lblTenSinhVien.setText(sv.getTenSinhVien());
        
        De d=ddao.selectByID(maDe);
        lblMaBaiThi.setText(maDe);
        lblSoCauHoi.setText(String.valueOf(d.getSoCauHoi()));
        lblThoiLuong.setText(String.valueOf(d.getThoigian())+" m");
        thoigian=d.getThoigian();
        soLuong=d.getSoCauHoi();
        lblMaMon.setText(d.getMaMon());
    }
    void sortRamdom(){
        listCH=(ArrayList<CauHoi>) chdao.selectAll();
        Collections.shuffle(listCH);
    }
    void createPanel() throws IOException, MalformedURLException, LineUnavailableException, UnsupportedAudioFileException{
        int lan2=0;
        int width= panelCauHoi.getWidth();
        int height= panelCauHoi.getHeight();
        for(int i =0 ;i<soLuong;i++){
            TabButton btn =new TabButton(i,listPanel);
            CauHoiPanel j =new CauHoiPanel(listCH.get(i),dadao.selectByMa(listCH.get(i).getMaCauHoi()),i,btn);
            Color randomColor = new Color((float)Math.random(), (float)Math.random(), (float)Math.random());
            j.setBackground(randomColor);
            listPanel.add(j);
            btn.setBackground(Color.white);
            btn.setText(String.valueOf(i+1));
            if(i>25){
                btn.setBounds(lan2*50, 30,50,30);
                lan2++;
            }else{
                btn.setBounds(i*50, 0,50,30);
            }
            listButton.add(btn);
            panelCauHoi.add(j);
            panelDieuKhien.add(btn);
            panelCauHoi.repaint();
            panelDieuKhien.repaint();
            
            
            
        }
    }
    public void demNguocF(){
        Thread demNguoc=new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        System.err.println(e);
                    }
                    if(giay==0){
                        thoigian--;
                        giay=60;
                    }
                    giay--;
                    if(giay<10){
                        lblThoiGian.setText(String.valueOf(thoigian)+" : 0"+String.valueOf(giay)); 
                    }else{
                        lblThoiGian.setText(String.valueOf(thoigian)+":"+String.valueOf(giay)); 
                    }
                    
                }
            }
        });
        
        
        demNguoc.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblThoiGian = new javax.swing.JLabel();
        panelCauHoi = new javax.swing.JPanel();
        panelDieuKhien = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        chkEnd = new javax.swing.JCheckBox();
        btnNop = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnBatDau = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMaSinhVien = new javax.swing.JLabel();
        lblTenSinhVien = new javax.swing.JLabel();
        lblMaBaiThi = new javax.swing.JLabel();
        lblSoCauHoi = new javax.swing.JLabel();
        lblThoiLuong = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMaMon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình thi");

        lblThoiGian.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        lblThoiGian.setForeground(new java.awt.Color(255, 51, 51));

        panelCauHoi.setBackground(new java.awt.Color(255, 255, 255));
        panelCauHoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCauHoi.setPreferredSize(new java.awt.Dimension(1061, 700));
        panelCauHoi.setLayout(new java.awt.CardLayout());

        panelDieuKhien.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout panelDieuKhienLayout = new javax.swing.GroupLayout(panelDieuKhien);
        panelDieuKhien.setLayout(panelDieuKhienLayout);
        panelDieuKhienLayout.setHorizontalGroup(
            panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDieuKhienLayout.setVerticalGroup(
            panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        chkEnd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chkEnd.setText("Bạn Muốn Kết Thúc Phần Thi");

        btnNop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNop.setText("Nộp Bài");
        btnNop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkEnd)
                .addGap(49, 49, 49)
                .addComponent(btnNop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEnd)
                    .addComponent(btnNop))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Mã Bài Thi");

        btnBatDau.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBatDau.setText("Bắt Đầu");
        btnBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatDauActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Thời Lượng");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Mã Sinh Viên:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Số Câu Hỏi");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Tên Sinh Viên: ");

        lblMaSinhVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMaSinhVien.setText("UD123123");

        lblTenSinhVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTenSinhVien.setText("Trương Anh Thọ");

        lblMaBaiThi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMaBaiThi.setText("De01");

        lblSoCauHoi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSoCauHoi.setText("30");

        lblThoiLuong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblThoiLuong.setText("90 m");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Mã Môn");

        lblMaMon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMaMon.setText("90 m");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblTenSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(lblMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(lblSoCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lblMaBaiThi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(29, 29, 29)
                                .addComponent(lblThoiLuong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMaMon)))
                        .addGap(84, 84, 84)
                        .addComponent(btnBatDau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addComponent(panelCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, 1317, Short.MAX_VALUE)
                    .addComponent(panelDieuKhien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(lblMaSinhVien))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(lblMaBaiThi)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(lblThoiLuong)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(lblSoCauHoi))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(lblTenSinhVien))
                                    .addComponent(lblMaMon)
                                    .addComponent(jLabel9)))
                            .addComponent(lblThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnBatDau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(panelCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(panelDieuKhien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    DiemDAO diemdao=new DiemDAO();
    private void btnNopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNopActionPerformed
        String sqlGiua="update diem set diemgiuaki = ? where masinhvien like ? and mamon like ?";
        String sqlCuối="update diem set diemcuoiki = ? where masinhvien like ? and mamon like ?";
        int soCauDung =0;
        if(chkEnd.isSelected()){
            for (CauHoiPanel cauHoi : listPanel) {
                if(cauHoi.trueFalse()){
                    soCauDung++;
                }
            }
            MsgBox.alert(this, "Bạn đúng "+soCauDung+" / "+soLuong);  
            De d =ddao.selectByID(lblMaBaiThi.getText());
            
            if(d.getKyThi().equals("Giữa kỳ")){
                JdbcHelper.update(sqlGiua,soCauDung/soLuong*10 ,lblMaSinhVien.getText(),lblMaMon.getText());
            }else if(d.getKyThi().equals("Cuối kỳ")){
                JdbcHelper.update(sqlCuối,soCauDung/soLuong*10,lblMaSinhVien.getText(),lblMaMon.getText() );
            }
            

            
            
            dispose();// TODO add your handling code here:
        }
        
    }//GEN-LAST:event_btnNopActionPerformed

    private void btnBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauActionPerformed
        demNguocF();
        sortRamdom();
        try {
            createPanel();
        } catch (IOException ex) {
            Logger.getLogger(ThiFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(ThiFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(ThiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnBatDau.setEnabled(false);
    }//GEN-LAST:event_btnBatDauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ThiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatDau;
    private javax.swing.JButton btnNop;
    private javax.swing.JCheckBox chkEnd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMaBaiThi;
    private javax.swing.JLabel lblMaMon;
    private javax.swing.JLabel lblMaSinhVien;
    private javax.swing.JLabel lblSoCauHoi;
    private javax.swing.JLabel lblTenSinhVien;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblThoiLuong;
    private javax.swing.JPanel panelCauHoi;
    private javax.swing.JPanel panelDieuKhien;
    // End of variables declaration//GEN-END:variables
}
